---
- name: install system tools
  dnf:
    name: "python3-libselinux,python3-firewall"
    state: present

- name: install PowerDNS
  dnf:
    name: "pdns,pdns-tools,pdns-backend-sqlite,sqlite"
    state: present
  notify:
    - reload_systemd

- name: check pdns config dir presence
  file:
    path: "{{ Fedora_pdns_config_dir }}"
    owner: root
    group: root
    mode: '0755'
    state: directory


- name: render pdns config
  template:
    src: pdns.conf.j2
    dest: "{{ Fedora_pdns_config }}"
    owner: root
    group: root
    mode: '0755'
  notify:
    reload_pdns

- name: Apply new SELinux file context to filesystem
  command: restorecon -irv "{{ Fedora_pdns_config }}"
